server:
  port: 9051

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  application:
    name: graph-database-service

    
spring.cloud.stream:
  function:
    definition: graphPlayerProcessor
  bindings:
    graphPlayerProcessor-in-0:
      destination: column-player-event
    graphPlayerProcessor-out-0:
      destination: graph-player-event

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true


