server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: columnar-key-value-service
          uri: lb://columnar-key-value-service
          predicates:
            - Path=/columnar-database-service/**
        - id: graph-spring-example
          uri: lb://graph-spring-example
          predicates:
            - Path=/graph-spring-example/**
